In [3]:
import pandas as pd

In [3]:
info = {
    "Name" : ["Vaibhavi", "Siddu", "Vaishnavi", "Madhu"],
    "CGPA" : [9.3, 9.5,8.9,9.9]
}
df = pd.DataFrame(info)
print(df)

        Name  CGPA
0   Vaibhavi   9.3
1      Siddu   9.5
2  Vaishnavi   8.9
3      Madhu   9.9

In [4]:
df

        Name  CGPA
0   Vaibhavi   9.3
1      Siddu   9.5
2  Vaishnavi   8.9
3      Madhu   9.9

In [6]:
series = pd.Series([1,2,3,4,5])
print(series)
print(type(series))

#index
print(series[0])
print(series[2])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
1
3

In [18]:
series = pd.Series([26, 54, 23, 53], index= ["Adam", "Eve", "Bob", "Charlie"])
print(series)

print(series["Adam"])
print(series["Bob"])
print(series[0])
print(series.index)

Adam       26
Eve        54
Bob        23
Charlie    53
dtype: int64
26
23
26
Index(['Adam', 'Eve', 'Bob', 'Charlie'], dtype='object')

C:\Users\WADHAVANE\AppData\Local\Temp\ipykernel_22052\161852526.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(series[0])

In [22]:
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([10,20,30,40,50])

print(s1 + s2)
s1[0] = 100
changed_s1 = s1.drop(0)
print(s1)
print(changed_s1)

0    11
1    22
2    33
3    44
4    55
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
# Dataframe

info = {
    "Name" : ["Vaibhavi", "Siddu", "Vaishnavi", "Madhu"],
    "Age" : [23,43,64,65],
    "CGPA" : [9.3, 9.5,8.9,9.9]
}
df = pd.DataFrame(info)
print(df, type(df))

print(df.index)
print(df.columns)

        Name  Age  CGPA
0   Vaibhavi   23   9.3
1      Siddu   43   9.5
2  Vaishnavi   64   8.9
3      Madhu   65   9.9 <class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=4, step=1)
Index(['Name', 'Age', 'CGPA'], dtype='object')

In [7]:
df.head()

   A  B  c
0  1  2  3
1  4  5  6

In [5]:
df

        Name  Age  CGPA
0   Vaibhavi   23   9.3
1      Siddu   43   9.5
2  Vaishnavi   64   8.9
3      Madhu   65   9.9

In [6]:
import numpy as np

np_arr = np.array([[1,2,3], [4,5,6]])
df = pd.DataFrame(np_arr, columns = ["A", "B", "c"])
print(df)

   A  B  c
0  1  2  3
1  4  5  6